services:
  - type: web
    name: pandy-n8n
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: n8n start
    envVars:
      - key: GENERIC_TIMEZONE
        value: America/Bogota
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: P4ndy$up3r*)
      - key: WEBHOOK_URL
        value: https://pandy-n8n.onrender.com/
